import { RenderLayer } from './Layers';

export type PlayerMapPreset = 'town' | 'region' | 'terrain' | 'hydrology' | 'planning';

export const PLAYER_MAP_PRESETS: Readonly<Record<PlayerMapPreset, readonly RenderLayer[]>> = {
  town: [
    RenderLayer.Terrain,
    RenderLayer.Zones,
    RenderLayer.Floodplains,
    RenderLayer.Rivers,
    RenderLayer.Islands,
    RenderLayer.IslandLabels,
    RenderLayer.Blocks,
    RenderLayer.BlockLabels,
    RenderLayer.Roads,
    RenderLayer.Bridges,
    RenderLayer.BridgeLabels,
    RenderLayer.Ports,
    RenderLayer.PortLabels,
    RenderLayer.RoadLabels,
    RenderLayer.Buildings,
    RenderLayer.Vegetation,
  ],
  region: [
    RenderLayer.Terrain,
    RenderLayer.Rivers,
    RenderLayer.Islands,
    RenderLayer.IslandLabels,
    RenderLayer.Roads,
    RenderLayer.Bridges,
    RenderLayer.BridgeLabels,
    RenderLayer.Ports,
    RenderLayer.PortLabels,
  ],
  terrain: [
    RenderLayer.Terrain,
    RenderLayer.Elevation,
    RenderLayer.Rivers,
    RenderLayer.Islands,
    RenderLayer.IslandLabels,
    RenderLayer.Bridges,
    RenderLayer.Ports,
  ],
  hydrology: [
    RenderLayer.Terrain,
    RenderLayer.Floodplains,
    RenderLayer.Rivers,
    RenderLayer.Islands,
    RenderLayer.Bridges,
    RenderLayer.Ports,
  ],
  planning: [
    RenderLayer.Terrain,
    RenderLayer.Islands,
    RenderLayer.IslandLabels,
    RenderLayer.Accessibility,
    RenderLayer.LandValue,
    RenderLayer.Zones,
    RenderLayer.Blocks,
    RenderLayer.BlockLabels,
    RenderLayer.Roads,
    RenderLayer.Bridges,
    RenderLayer.BridgeLabels,
    RenderLayer.Ports,
    RenderLayer.PortLabels,
    RenderLayer.RoadLabels,
    RenderLayer.Buildings,
  ],
};

export const PLAYER_SAFE_MAP_LAYERS: readonly { readonly layer: RenderLayer; readonly label: string }[] = [
  { layer: RenderLayer.Terrain, label: 'Terrain' },
  { layer: RenderLayer.Elevation, label: 'Elevation' },
  { layer: RenderLayer.Moisture, label: 'Moisture' },
  { layer: RenderLayer.Temperature, label: 'Temperature' },
  { layer: RenderLayer.Accessibility, label: 'Accessibility' },
  { layer: RenderLayer.LandValue, label: 'Land value' },
  { layer: RenderLayer.Zones, label: 'Zones' },
  { layer: RenderLayer.Floodplains, label: 'Flood risk' },
  { layer: RenderLayer.Rivers, label: 'Rivers' },
  { layer: RenderLayer.Islands, label: 'Island boundaries' },
  { layer: RenderLayer.IslandLabels, label: 'Island labels' },
  { layer: RenderLayer.Blocks, label: 'Blocks' },
  { layer: RenderLayer.BlockLabels, label: 'Block labels' },
  { layer: RenderLayer.Roads, label: 'Roads' },
  { layer: RenderLayer.RoadLabels, label: 'Road labels' },
  { layer: RenderLayer.Bridges, label: 'Bridges' },
  { layer: RenderLayer.BridgeLabels, label: 'Bridge labels' },
  { layer: RenderLayer.Ports, label: 'Ports' },
  { layer: RenderLayer.PortLabels, label: 'Port labels' },
  { layer: RenderLayer.Buildings, label: 'Buildings' },
  { layer: RenderLayer.Vegetation, label: 'Vegetation' },
];

export const GM_MAP_VIEW_PRESETS: Readonly<Record<string, readonly RenderLayer[]>> = {
  town: [
    RenderLayer.Terrain,
    RenderLayer.Islands,
    RenderLayer.IslandLabels,
    RenderLayer.Settlements,
    RenderLayer.Zones,
    RenderLayer.Blocks,
    RenderLayer.BlockLabels,
    RenderLayer.Rivers,
    RenderLayer.Roads,
    RenderLayer.Bridges,
    RenderLayer.BridgeLabels,
    RenderLayer.Ports,
    RenderLayer.PortLabels,
    RenderLayer.RoadLabels,
    RenderLayer.Buildings,
    RenderLayer.CustomImages,
    RenderLayer.Vegetation,
    RenderLayer.Anchors,
    RenderLayer.Story,
    RenderLayer.NPCs,
    RenderLayer.Authoring,
    RenderLayer.Travel,
  ],
  story: [
    RenderLayer.Terrain,
    RenderLayer.Islands,
    RenderLayer.IslandLabels,
    RenderLayer.Settlements,
    RenderLayer.Rivers,
    RenderLayer.Roads,
    RenderLayer.Bridges,
    RenderLayer.BridgeLabels,
    RenderLayer.Ports,
    RenderLayer.PortLabels,
    RenderLayer.RoadLabels,
    RenderLayer.Buildings,
    RenderLayer.CustomImages,
    RenderLayer.Vegetation,
    RenderLayer.Anchors,
    RenderLayer.Story,
    RenderLayer.NPCs,
    RenderLayer.Authoring,
    RenderLayer.HiddenPayaw,
    RenderLayer.Travel,
  ],
  terrain: PLAYER_MAP_PRESETS.terrain,
  hydrology: PLAYER_MAP_PRESETS.hydrology,
  planning: [
    ...PLAYER_MAP_PRESETS.planning,
    RenderLayer.Settlements,
    RenderLayer.Anchors,
    RenderLayer.Authoring,
  ],
};
